steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/my-representatives-489301/cloud-run-source-deploy/my-representatives/my-reps-frontend:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '--build-arg'
      - 'VITE_GOOGLE_PLACES_API_KEY=${_VITE_GOOGLE_PLACES_API_KEY}'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'my-reps-frontend'
      - '--image'
      - 'us-east1-docker.pkg.dev/my-representatives-489301/cloud-run-source-deploy/my-representatives/my-reps-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-east1'

images:
  - 'us-east1-docker.pkg.dev/my-representatives-489301/cloud-run-source-deploy/my-representatives/my-reps-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _VITE_API_URL: ''
  _VITE_GOOGLE_PLACES_API_KEY: ''
